### ISSUE TITLE
Dataset larger than memory

### ISSUE THREAD

**Issue by abreufilho** [Bobholamovic/CDLab#1]
Hello! I've been using the official repo by rcdaudt but that one cannot load dataset bigger than RAM.

Does your implementation load the datasets on the fly or loads everything at once at RAM?

**Comment by Bobholamovic** [comment]
This repo currently supports four datasets, namely AirChange-Szada, AirChange-Tiszadob, Lebedev, and OSCD.

For the AirChange datasets, LRU caches are used for loading images and labels, as can be seen [here](https://github.com/Bobholamovic/CDLab/blob/b85907011c3a9564e87c338190ed0149f4f3ba88/src/data/_airchange.py#L49) and [here](https://github.com/Bobholamovic/CDLab/blob/b85907011c3a9564e87c338190ed0149f4f3ba88/src/data/_airchange.py#L54). That is, each sample is loaded and cached in the RAM the first time it is requested. If you want no-cache, remove these two lines from the code.

For the Lebedev dataset, no cache is used and the samples are loaded on the fly.

For the OSCD dataset, you can set `cache_level` of the initializer to choose a caching level. Specifically, `cache_level=0` for no cache, `1` to cache binary labels only, and `2` and higher to cache both images and labels. The default `cache_level` is `2` for both training and evaluation, which is set [here](https://github.com/Bobholamovic/CDLab/blob/b85907011c3a9564e87c338190ed0149f4f3ba88/src/impl/builders/data_builders.py#L120) and [here](https://github.com/Bobholamovic/CDLab/blob/b85907011c3a9564e87c338190ed0149f4f3ba88/src/impl/builders/data_builders.py#L142). However, it is recommended that you can modify these arguments according to your needs.
