### ISSUE TITLE
--tb_on flag

### ISSUE THREAD

**Issue by abreufilho** [Bobholamovic/CDLab#2]
Is "--tb_on" flag working as intended?

On my code, whenever i enable "tb_on", i get the following message:

```
Traceback (most recent call last):
  File "train.py", line 68, in <module>
    main()
  File "train.py", line 64, in main
    raise NotImplementedError("Cannot find an appropriate trainer.")
NotImplementedError: Cannot find an appropriate trainer.
```

I have tried to modify some stuff but nothing makes the tensorboard summaries appear. Am i missing something or this functionality is not ready?

**Comment by abreufilho** [comment]
By the way, i am using OSCD dataset.

**Comment by Bobholamovic** [comment]
Note that currently OSCD does not support TensorBoard visualization because it contans more than three bands.

**Comment by abreufilho** [comment]
Alright. Would it be possible to to save at Tensorboard using only RGB or RGIR for visualization purposes only? Even if i am using all the bands in the training phase?

**Comment by Bobholamovic** [comment]
Yes, this is possible. And I'm considering adding this feature in the future.

**Comment by Bobholamovic** [comment]
Hi, now OSCD dataset can be trained with `tb_on` flag set. I'm closing this issue. If you have further questions, please do not hesitate to open another issue.
