### ISSUE TITLE
关于WHU数据集划分

### ISSUE THREAD

**Issue by JackLiu-97** [Bobholamovic/CDLab#22]
您好，你在划分WHU数据集时是如何划分WHU数据集的，是使用项目中提供的preprocess_whu,py还是preprocess_whu_random.py来处理数据集的，其中preprocess_whu_random.py处理后的whu数据集，为什么测试集比训练集多好多？

**Comment by Bobholamovic** [comment]
你好，可以根据需要选择使用的脚本：
- `preprocess_whu.py`脚本将大图被切成3块，保证验证集对应的区域将训练集和测试集完全隔开。这是提出数据集的原始论文中的标准划分方式。
- `preprocess_whu_random.py`脚本则将大图切成指定大小的块，然后将切出的图像块随机划分成训练、验证、测试集。近几年许多论文采用了这种划分方式（因为混合了场景所以看起来在测试集上的精度一般更高）。

此外，在脚本中可以设置训练集、验证集和测试集样本的比例，以控制每个子集的样本数量。

**Comment by JackLiu-97** [comment]
您在训练时是使用preprocess_whu_random.py 来划分数据集的吗？

**Comment by Bobholamovic** [comment]
请问你说的是P2V-CD模型嘛？我使用的是`preprocess_whu_random.py`，正如论文中描述的：
![image](https://github.com/Bobholamovic/CDLab/assets/21275753/5add139f-cc96-4b97-abdb-190ef93448fe)

**Comment by JackLiu-97** [comment]
好的，感谢您的回答！祝您生活愉快~
