### ISSUE TITLE
你好，我是小白，关于数据集裁剪为256*256大小的问题

### ISSUE THREAD

**Issue by Starryskyee** [Bobholamovic/CDLab#39]
我翻阅了前面提问的数据集裁剪问题，用了针对LEVIRCD数据集的裁剪脚本preprocess_levir_cd.py，得到的图片文件夹是
这样的：![111](https://github.com/Bobholamovic/CDLab/assets/119586658/c88a874a-fd6a-41ab-a2b9-07eef535a9cc)
![222](https://github.com/Bobholamovic/CDLab/assets/119586658/56ff651b-2288-4710-9dd8-c0e3d413e0e8)
并不是源文件夹的那种结构了，这个应该怎么处理呢？

**Comment by Bobholamovic** [comment]
你好，那个脚本的预期输出就是这样的，应该只需要把配置文件中的数据集路径替换成裁剪后的数据集根目录就可以正常使用～
