### ISSUE TITLE
为什么我跑得时候程序只使用cpu在跑

### ISSUE THREAD

**Issue by yy2019python** [Bobholamovic/CDLab#4]
如题

**Comment by Bobholamovic** [comment]
是否指定了`--device`选项为`cpu`呢？

**Comment by yy2019python** [comment]
device设定的是cuda，而且在使用levircd数据集时，会outofmemory，采用的bs是8，请问你采用的GPU是什么，会不会是因为我的显卡是GTX1660Ti的原因

**Comment by yy2019python** [comment]
![7](https://user-images.githubusercontent.com/50469453/167357813-06fdc2b5-76be-477c-a1b1-46efaded42b1.jpg)

**Comment by yy2019python** [comment]
![2](https://user-images.githubusercontent.com/50469453/167358038-8e7148ef-1e50-4491-8849-d2b38b91bb22.jpg)

**Comment by yy2019python** [comment]
好像解决了，多谢
