### ISSUE TITLE
Request for pretrained weight

### ISSUE THREAD

**Issue by hoangminhtoan** [Bobholamovic/CDLab#40]
Hi, 
I want to request a pre-trained weight if you don't mind. I just want to have quick results on my dataset.

**Comment by Bobholamovic** [comment]
Hi, this repo is a piece of work I did at school, and I didn't make a copy of the pre-trained weights before graduating, so I'm not able to provide them. Having said so, it is easy and cheap to train a network from scratch using this repo. If you have any further questions, please feel free to open an issue.

**Comment by hoangminhtoan** [comment]
Thank you for your reply. I'll try to train the model as you suggested.
