### ISSUE TITLE
关于使用grad-cam可视化

### ISSUE THREAD

**Issue by adleess** [Bobholamovic/CDLab#42]
大佬我想请问下，使用你的模型训练后，我使用grad-cam进行可视化，无论选哪层都会报错： grad can be implicitly created only for scalar outputs。你能分享下你使用grad-cam的一些改动吗

**Comment by Bobholamovic** [comment]
你好，时间有点儿久了，我也不太记得之前自己做了哪些改动。不过，关于“grad can be implicitly created only for scalar outputs”这个问题，很可能是因为用于反向传播的loss不是标量，并且也没有为`backward`方法显式指定预期形状的梯度张量。具体可以参考网上的一些帖子：
https://discuss.pytorch.org/t/runtimeerror-grad-can-be-implicitly-created-only-for-scalar-outputs-in-one-gpu/161389
https://discuss.pytorch.org/t/loss-backward-raises-error-grad-can-be-implicitly-created-only-for-scalar-outputs/12152/2

**Comment by adleess** [comment]
> 你好，时间有点儿久了，我也不太记得之前自己做了哪些改动。不过，关于“grad can be implicitly created only for scalar outputs”这个问题，很可能是因为用于反向传播的loss不是标量，并且也没有为`backward`方法显式指定预期形状的梯度张量。具体可以参考网上的一些帖子： https://discuss.pytorch.org/t/runtimeerror-grad-can-be-implicitly-created-only-for-scalar-outputs-in-one-gpu/161389 https://discuss.pytorch.org/t/loss-backward-raises-error-grad-can-be-implicitly-created-only-for-scalar-outputs/12152/2

好的，感谢你的回复！
