### ISSUE TITLE
The label of the CDD　dataset is not binary map.

### ISSUE THREAD

**Issue by yiyi-today** [Bobholamovic/CDLab#5]
Thank you for your generous sharing！

I downloaded the CDD dataset mentioned in your paper, but found that the label of the CDD dataset was not binary map, as Issue in label dataset of 2018. Lebedev M A, Vizilter Y V, Vygolov O V, et al. Change detection in remote sensing images using conditional adversarial networks said.

How did you deal with this situation ?

thanks

**Comment by Bobholamovic** [comment]
I binarize the labels with 127 as the threshold. See 
https://github.com/Bobholamovic/CDLab/blob/4cab42ebe60a95203e5b67f6680947e9a559eed6/src/data/svcd.py#L50

**Comment by yiyi-today** [comment]
> I binarize the labels with 127 as the threshold. See
> 
> https://github.com/Bobholamovic/CDLab/blob/4cab42ebe60a95203e5b67f6680947e9a559eed6/src/data/svcd.py#L50



> I binarize the labels with 127 as the threshold. See
> 
> https://github.com/Bobholamovic/CDLab/blob/4cab42ebe60a95203e5b67f6680947e9a559eed6/src/data/svcd.py#L50

Thanks a lot for your answer, but what is the special meaning of using 127? If you normalize all values to 0-1, there will be many noisy points, is this normal?
![1653618462(1)](https://user-images.githubusercontent.com/57097748/170616602-cb8bb3dd-375c-4d66-9ca2-bc569e6c820d.jpg)

**Comment by Bobholamovic** [comment]
> > I binarize the labels with 127 as the threshold. See
> > https://github.com/Bobholamovic/CDLab/blob/4cab42ebe60a95203e5b67f6680947e9a559eed6/src/data/svcd.py#L50
> 
> > I binarize the labels with 127 as the threshold. See
> > https://github.com/Bobholamovic/CDLab/blob/4cab42ebe60a95203e5b67f6680947e9a559eed6/src/data/svcd.py#L50
> 
> Thanks a lot for your answer, but what is the special meaning of using 127? If you normalize all values to 0-1, there will be many noisy points, is this normal? ![1653618462(1)](https://user-images.githubusercontent.com/57097748/170616602-cb8bb3dd-375c-4d66-9ca2-bc569e6c820d.jpg)

1. The numeric range of uint8 type is [0,255], while 127 is (0+255)//2.
2. A binarization result like this might be *normal*, depending on the threshold you use.

**Comment by yiyi-today** [comment]
> > > I binarize the labels with 127 as the threshold. See
> > > https://github.com/Bobholamovic/CDLab/blob/4cab42ebe60a95203e5b67f6680947e9a559eed6/src/data/svcd.py#L50
> > 
> > 
> > > I binarize the labels with 127 as the threshold. See
> > > https://github.com/Bobholamovic/CDLab/blob/4cab42ebe60a95203e5b67f6680947e9a559eed6/src/data/svcd.py#L50
> > 
> > 
> > Thanks a lot for your answer, but what is the special meaning of using 127? If you normalize all values to 0-1, there will be many noisy points, is this normal? ![1653618462(1)](https://user-images.githubusercontent.com/57097748/170616602-cb8bb3dd-375c-4d66-9ca2-bc569e6c820d.jpg)
> 
> 1. The numeric range of uint8 type is [0,255], while 127 is (0+255)//2.
> 2. A binarization result like this might be _normal_, depending on the threshold you use.

Thank you and have a nice life！
