### ISSUE TITLE
骨干网络修改

### ISSUE THREAD

**Issue by yy2019python** [Bobholamovic/CDLab#6]
我在将BIT网络主干部分换成resnet50的时候会报错，RuntimeError: Given groups=1, weight of size [32, 256, 3, 3], expected input[1, 1024, 258, 258] to have 256 channels, but got 1024 channels instead

**Comment by Bobholamovic** [comment]
因为ResNet-50使用了BottleneckBlock而不是BasicBlock作为基础组件，所以需要对应修改backbone的输出通道数。

**Comment by yy2019python** [comment]
谢谢你的建议，我好像修改好了，但是不知道效果好不好，如果不错的话，请问我能将我修改的文件提交到您的项目中吗

**Comment by Bobholamovic** [comment]
当然可以，欢迎提PR～
