### ISSUE TITLE
预训练模型是否可以提供

### ISSUE THREAD

**Issue by hnsywangxin** [Bobholamovic/CDLab#8]
打算用p2v算法去训练自己的数据集，但是好像找不到预训练模型，希望可以提供一下，谢谢

**Comment by Bobholamovic** [comment]
你好，最近我可能暂时没有精力维护这个仓库……按照默认的配置文件，使用较少的资源（我记得训练的显存占用应该是10 G出头，只需要单卡训练）就可以复现精度。建议你可以先尝试训练一下哈，如果遇到问题的话欢迎讨论～

**Comment by hnsywangxin** [comment]
收到，谢谢
